make re
echo charfc1
./cub3D test/charfc1.cub
echo charfc2
./cub3D test/charfc2.cub
echo charfc3
./cub3D test/charfc3.cub
echo charfc4
./cub3D test/charfc4.cub
echo charfc5
./cub3D test/charfc5.cub
echo charfc
./cub3D test/charfc.cub
echo elmap1
./cub3D test/elmap1.cub
echo elmap
./cub3D test/elmap.cub
echo hole10
./cub3D test/hole10.cub
echo hole11
./cub3D test/hole11.cub
echo hole12
./cub3D test/hole12.cub
echo hole13
./cub3D test/hole13.cub
echo hole14
./cub3D test/hole14.cub
echo hole15
./cub3D test/hole15.cub
echo hole1
./cub3D test/hole1.cub
echo hole2
./cub3D test/hole2.cub
echo hole3
./cub3D test/hole3.cub
echo hole4
./cub3D test/hole4.cub
echo hole5
./cub3D test/hole5.cub
echo hole6
./cub3D test/hole6.cub
echo hole7
./cub3D test/hole7.cub
echo hole8
./cub3D test/hole8.cub
echo hole9
./cub3D test/hole9.cub
echo hole
./cub3D test/hole.cub
echo infmis10
./cub3D test/infmis10.cub
echo infmis11
./cub3D test/infmis11.cub
echo infmis1
./cub3D test/infmis1.cub
echo infmis2
./cub3D test/infmis2.cub
echo infmis3
./cub3D test/infmis3.cub
echo infmis4
./cub3D test/infmis4.cub
echo infmis5
./cub3D test/infmis5.cub
echo infmis6
./cub3D test/infmis6.cub
echo infmis7
./cub3D test/infmis7.cub
echo infmis8
./cub3D test/infmis8.cub
echo infmis9
./cub3D test/infmis9.cub
echo infmis
./cub3D test/infmis.cub
echo invalid1
./cub3D test/invalid1.cub
echo invalid2
./cub3D test/invalid2.cub
echo map.xpm.cub
./cub3D test/map.xpm.cub
echo invcbl2
./cub3D test/invcbl2.cub
echo invcbl3
./cub3D test/invcbl3.cub
echo invcbl4
./cub3D test/invcbl4.cub
echo invcbl5
./cub3D test/invcbl5.cub
echo invcbl
./cub3D test/invcbl.cub
echo invcharfile1
./cub3D test/invcharfile1.cub
echo invcharfile2
./cub3D test/invcharfile2.cub
echo invcharfile3
./cub3D test/invcharfile3.cub
echo invcharfile4
./cub3D test/invcharfile4.cub
echo invcharfile5
./cub3D test/invcharfile5.cub
echo invcharfile
./cub3D test/invcharfile.cub
echo invcharmap1
./cub3D test/invcharmap1.cub
echo invcharmap2
./cub3D test/invcharmap2.cub
echo invcharmap3
./cub3D test/invcharmap3.cub
echo invcharmap4
./cub3D test/invcharmap4.cub
echo invcharmap5
./cub3D test/invcharmap5.cub
echo invcharmap6
./cub3D test/invcharmap6.cub
echo invcharmap7
./cub3D test/invcharmap7.cub
echo invcharmap8
./cub3D test/invcharmap8.cub
echo invcharmap
./cub3D test/invcharmap.cub
echo invctex1
./cub3D test/invctex1.cub
echo invctex2
./cub3D test/invctex2.cub
echo invctex3
./cub3D test/invctex3.cub
echo invctex
./cub3D test/invctex.cub
echo invres1
./cub3D test/invres1.cub
echo invres2
./cub3D test/invres2.cub
echo invres3
./cub3D test/invres3.cub
echo invres4
./cub3D test/invres4.cub
echo invres5
./cub3D test/invres5.cub
echo invres6
./cub3D test/invres6.cub
echo invres
./cub3D test/invres.cub
echo invtex1
./cub3D test/invtex1.cub
echo invtex2
./cub3D test/invtex2.cub
echo invtex3
./cub3D test/invtex3.cub
echo invtex4
./cub3D test/invtex4.cub
echo invtex
./cub3D test/invtex.cub
echo map.c
./cub3D test/map.c
echo map.cu
./cub3D test/map.cu
echo mapcub
./cub3D test/mapcub
echo map.cub5
./cub3D test/map.cub5
echo map.cubqreyhutfsdfg
./cub3D test/map.cubqreyhutfsdfg
echo map.cubu
./cub3D test/map.cubu
echo map.xpm
./cub3D test/map.xpm
echo invalid_argument
./cub3D test/map.cub hey
echo invalid_argument 1
./cub3D
echo miscom1
./cub3D test/miscom1.cub
echo miscom2
./cub3D test/miscom2.cub
echo miscom3
./cub3D test/miscom3.cub
echo miscom
./cub3D test/miscom.cub
echo mismap
./cub3D test/mismap.cub
echo mismap1
./cub3D test/mismap1.cub
echo mulfc1
./cub3D test/mulfc1.cub
echo mulfc
./cub3D test/mulfc.cub
echo mulinvtex2
./cub3D test/mulinvtex2.cub
echo mulinvtex3
./cub3D test/mulinvtex3.cub
echo mulinvtex4
./cub3D test/mulinvtex4.cub
echo mulinvtex5
./cub3D test/mulinvtex5.cub
echo mulinvtex6
./cub3D test/mulinvtex6.cub
echo mulinvtex7
./cub3D test/mulinvtex7.cub
echo mulinvtex8
./cub3D test/mulinvtex8.cub
echo mulinvtex
./cub3D test/mulinvtex.cub
echo mulplay1
./cub3D test/mulplay1.cub
echo mulplay2
./cub3D test/mulplay2.cub
echo mulplay3
./cub3D test/mulplay3.cub
echo mulplay4
./cub3D test/mulplay4.cub
echo mulplay
./cub3D test/mulplay.cub
echo mulres1
./cub3D test/mulres1.cub
echo mulres2
./cub3D test/mulres2.cub
echo mulres3
./cub3D test/mulres3.cub
echo mulres4
./cub3D test/mulres4.cub
echo mulres
./cub3D test/mulres.cub
echo nenum1
./cub3D test/nenum1.cub
echo nenum
./cub3D test/nenum.cub
echo noplay
./cub3D test/noplay.cub
echo rgbvalue1
./cub3D test/rgbvalue1.cub
echo rgbvalue2
./cub3D test/rgbvalue2.cub
echo rgbvalue
./cub3D test/rgbvalue.cub
echo tmnum1
./cub3D test/tmnum1.cub
echo tmnum2
./cub3D test/tmnum2.cub
echo tmnum
./cub3D test/tmnum.cub